version: '3'

tasks:
  run:
    cmds:
      - cd src && go run main.go
  
  docker-build:
    cmds:
      - docker build -t webserver .
  
  docker-run:
    cmds:
      - docker run -p "8080:8080" webserver:latest