name: Deploy - PreProcessor

on:
  push:
    paths:
      - 'preprocessor/**'
      - '.github/workflows/deploy-preprocessor.yaml'

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  SERVICE_NAME: preprocessor

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/835830097908/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions@go-wayback.iam.gserviceaccount.com'
    
    - name: "gcloud info"
      run: |
        gcloud storage ls

    - name: Configure Docker
      run: |
        gcloud --quiet auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/$GCP_PROJECT/$SERVICE_NAME:$GITHUB_SHA preprocessor/
        docker push gcr.io/$GCP_PROJECT/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$GCP_PROJECT/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region europe-west3 \
          --allow-unauthenticated \
          --max-instances 2
