name: Print GitHub Context Variables

on: [push]

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print GitHub Context
      run: |
        echo "GitHub context:"
        echo "----------------"
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

