name: Terraform

on:
  push:
    paths:
      - 'infrastructure/**'
      - '.github/workflows/terraform.yaml'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.x
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform -chdir=infrastructure fmt -check

      - name: Terraform Init
        run: terraform -chdir=infrastructure init

      - name: Terraform Validate
        run: terraform -chdir=infrastructure validate

      - name: Terraform Plan
        run: terraform -chdir=infrastructure plan -out=plan.tfplan

      - name: Terraform Apply
        run: terraform -chdir=infrastructure apply -auto-approve plan.tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}
